# Converting Words to Vectors

After text preprocessing, we will now try to give meaning to each word for the computer to understand. This where we apply different techniques to convert each word to vectors. Some of the techniques used are:
* One Hot Encoding (OHE)
* Bag Of Words (BOW)
* Term Frequency-Inverse Document Frequency (TF-IDF)
* Word2Vec
* AvgWord2Vec

Visit your note for the application of these techniques and how they work. Identify their advantage and disadvantage.

## BAG OF WORDS

In [1]:
import pandas as pd
messages=pd.read_csv("SMSSpamCollection.txt",sep='\t',names=['label','message'])

## '\t' is a tab separated variable

In [2]:
messages.head()

,label,message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."


In [3]:
## Data cleaning and preprocessing
import re ## import regular-expression
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\pc\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [4]:
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

ps=PorterStemmer()

In [5]:
corpus=[]
for i in range(0,len(messages)):
    ## remove special characters
    review=re.sub('[^a-zA-z]', ' ', messages['message'][i]) ## This says- apart from small and capital a-z any other thing you find replace it with blankspace. Perform this is in the data provided
    review=review.lower()
    review_words=review.split()
    stemmed_review_words=[ps.stem(word) for word in review_words if not word in stopwords.words('english')]
    stemmed_review_sentence=' '.join(stemmed_review_words)
    corpus.append(stemmed_review_sentence)

In [6]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

In [7]:
## Create the bag of words (BOW) model
## We will use sklearn's CountVectorizer for this
from sklearn.feature_extraction.text import CountVectorizer


In [8]:
countvectorizer=CountVectorizer(max_features=2500)
## max_features=2500 is saying that out of all the words in the BOW take the top 2500 words
## for binary BOW set binary=True

In [9]:
X=countvectorizer.fit_transform(corpus).toarray()

In [10]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [11]:
X.shape

(5572, 2500)

### N Grams

We use this to create combination of words for improved sentence to vector transformation. Examples are unigram, bigrams, trigram etc

We will work an exampleon how to use N-grams

In [12]:
## Create bag of words model
from sklearn.feature_extraction.text import CountVectorizer
## for binary BOW
cv=CountVectorizer(max_features=100,binary=True)

In [13]:
X=cv.fit_transform(corpus).toarray()

In [14]:
import numpy as np
np.set_printoptions(
    edgeitems=30,
    linewidth=100000,
    formatter=dict(float=lambda x: "%.3g" % x))

X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0

In [15]:
cv.vocabulary_ ## These re the top 100 vocabularies with their column index

{'go': 22,
 'great': 25,
 'got': 24,
 'wat': 90,
 'ok': 56,
 'free': 18,
 'win': 94,
 'text': 77,
 'txt': 85,
 'say': 67,
 'alreadi': 0,
 'think': 80,
 'hey': 28,
 'week': 92,
 'back': 3,
 'like': 38,
 'still': 73,
 'send': 69,
 'even': 15,
 'friend': 19,
 'prize': 62,
 'claim': 7,
 'call': 4,
 'mobil': 47,
 'co': 8,
 'home': 30,
 'want': 89,
 'today': 82,
 'cash': 6,
 'day': 12,
 'repli': 64,
 'www': 96,
 'right': 65,
 'thank': 78,
 'take': 75,
 'time': 81,
 'use': 87,
 'messag': 44,
 'oh': 55,
 'ye': 97,
 'make': 42,
 'way': 91,
 'feel': 16,
 'dont': 14,
 'miss': 46,
 'ur': 86,
 'tri': 84,
 'da': 11,
 'lor': 39,
 'meet': 43,
 'realli': 63,
 'get': 20,
 'know': 33,
 'love': 40,
 'let': 37,
 'work': 95,
 'wait': 88,
 'yeah': 98,
 'tell': 76,
 'pleas': 61,
 'msg': 49,
 'see': 68,
 'pl': 60,
 'need': 51,
 'tomorrow': 83,
 'hope': 31,
 'well': 93,
 'lt': 41,
 'gt': 26,
 'ask': 1,
 'morn': 48,
 'happi': 27,
 'sorri': 72,
 'give': 21,
 'new': 52,
 'find': 17,
 'year': 99,
 'later': 35,
 'pi

In [16]:
len(cv.vocabulary_)

100

In [17]:
## Now let us implement n-gram
## Create the Bag Of Words model with ngram
from sklearn.feature_extraction.text import CountVectorizer
## for Binary BOW enable binary=True
cv=CountVectorizer(max_features=100,binary=True,ngram_range=(1,1)) 
## with ngram_range as (1,1) the values will be tha same as the previous. This is unigram
X=cv.fit_transform(corpus).toarray()

In [18]:
cv.vocabulary_

{'go': 22,
 'great': 25,
 'got': 24,
 'wat': 90,
 'ok': 56,
 'free': 18,
 'win': 94,
 'text': 77,
 'txt': 85,
 'say': 67,
 'alreadi': 0,
 'think': 80,
 'hey': 28,
 'week': 92,
 'back': 3,
 'like': 38,
 'still': 73,
 'send': 69,
 'even': 15,
 'friend': 19,
 'prize': 62,
 'claim': 7,
 'call': 4,
 'mobil': 47,
 'co': 8,
 'home': 30,
 'want': 89,
 'today': 82,
 'cash': 6,
 'day': 12,
 'repli': 64,
 'www': 96,
 'right': 65,
 'thank': 78,
 'take': 75,
 'time': 81,
 'use': 87,
 'messag': 44,
 'oh': 55,
 'ye': 97,
 'make': 42,
 'way': 91,
 'feel': 16,
 'dont': 14,
 'miss': 46,
 'ur': 86,
 'tri': 84,
 'da': 11,
 'lor': 39,
 'meet': 43,
 'realli': 63,
 'get': 20,
 'know': 33,
 'love': 40,
 'let': 37,
 'work': 95,
 'wait': 88,
 'yeah': 98,
 'tell': 76,
 'pleas': 61,
 'msg': 49,
 'see': 68,
 'pl': 60,
 'need': 51,
 'tomorrow': 83,
 'hope': 31,
 'well': 93,
 'lt': 41,
 'gt': 26,
 'ask': 1,
 'morn': 48,
 'happi': 27,
 'sorri': 72,
 'give': 21,
 'new': 52,
 'find': 17,
 'year': 99,
 'later': 35,
 'pi

In [19]:
## Create the Bag Of Words model with ngram
from sklearn.feature_extraction.text import CountVectorizer
## for Binary BOW enable binary=True
cv=CountVectorizer(max_features=200,binary=True,ngram_range=(1,2)) 
## max features increased to 200 for more illustration
## with ngram_range as (1,2). Here we combine unigram and bigram
X=cv.fit_transform(corpus).toarray()

In [20]:
cv.vocabulary_

{'go': 51,
 'great': 55,
 'got': 54,
 'wat': 183,
 'ok': 117,
 'free': 47,
 'win': 189,
 'st': 153,
 'may': 94,
 'text': 161,
 'txt': 174,
 'dun': 37,
 'say': 138,
 'alreadi': 0,
 'think': 164,
 'live': 83,
 'around': 5,
 'hey': 65,
 'week': 186,
 'word': 191,
 'back': 9,
 'like': 81,
 'still': 155,
 'send': 140,
 'even': 40,
 'per': 120,
 'friend': 48,
 'custom': 31,
 'prize': 132,
 'claim': 22,
 'call': 14,
 'hour': 70,
 'mobil': 101,
 'month': 103,
 'co': 23,
 'gonna': 52,
 'home': 68,
 'soon': 150,
 'want': 182,
 'talk': 159,
 'tonight': 172,
 'today': 168,
 'cash': 19,
 'cost': 29,
 'day': 33,
 'repli': 135,
 'urgent': 177,
 'www': 194,
 'right': 136,
 'thank': 162,
 'take': 158,
 'help': 64,
 'time': 167,
 'use': 179,
 'next': 110,
 'messag': 97,
 'com': 26,
 'oh': 116,
 'watch': 184,
 'name': 107,
 'ye': 196,
 'make': 91,
 'fine': 44,
 'way': 185,
 'feel': 42,
 'dont': 36,
 'miss': 100,
 'ur': 176,
 'tri': 173,
 'first': 46,
 'da': 32,
 'finish': 45,
 'lor': 86,
 'meet': 96,
 'r

If you go through the dictionary you will find some double word combination. Please refer to note for detailed explanation

In [21]:
from sklearn.feature_extraction.text import CountVectorizer
## for Binary BOW enable binary=True
cv=CountVectorizer(max_features=200,binary=True,ngram_range=(2,2)) 
## max features increased to 200 for more illustration
## with ngram_range as (2,2). Here we combine using bigram only (ignoring unigram)
X=cv.fit_transform(corpus).toarray()

In [22]:
cv.vocabulary_

{'free entri': 55,
 'rate appli': 134,
 'claim call': 28,
 'call claim': 8,
 'claim code': 29,
 'free call': 54,
 'call mobil': 16,
 'chanc win': 27,
 'txt word': 177,
 'let know': 94,
 'feel like': 52,
 'repli ye': 140,
 'go home': 64,
 'call repli': 20,
 'mobil free': 107,
 'pleas call': 126,
 'lt gt': 102,
 'miss call': 105,
 'want go': 191,
 'first time': 53,
 'like lt': 95,
 'sm ac': 152,
 'sorri call': 153,
 'call later': 14,
 'award bonu': 5,
 'prize call': 131,
 'ur award': 180,
 'call free': 10,
 'that cool': 167,
 'call custom': 9,
 'custom servic': 40,
 'servic repres': 149,
 'guarante cash': 75,
 'cash prize': 26,
 'po box': 127,
 'tri contact': 172,
 'draw show': 45,
 'show prize': 150,
 'prize guarante': 133,
 'guarante call': 74,
 'valid hr': 187,
 'select receiv': 146,
 'speak live': 154,
 'live oper': 98,
 'privat account': 130,
 'account statement': 0,
 'statement show': 157,
 'call identifi': 11,
 'identifi code': 88,
 'code expir': 33,
 'urgent mobil': 185,
 'bonu c

You can do the same for trigram (3,3). Note:(1,3) will run unigram, bigram and trigram. When training you can run hyperparameters to test different combinations to get the best accuracy.

## TEXT FREQUENCY-INVERSE DOCUMENT FREQUENCY (TF-IDF)

Check note for explanation.

We will carry out the same process we carried out before.

In [23]:
import pandas as pd
messages=pd.read_csv('SMSSpamCollection.txt',sep='\t',names=['label','message'])
messages

,label,message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."
...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...
5568,ham,Will ü b going to esplanade fr home?
5569,ham,"Pity, * was in mood for that. So...any other s..."
5570,ham,The guy did some bitching but I acted like i'd...


In [24]:
## Data Cleaning And Preprocessing
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\pc\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [27]:
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
wnl=WordNetLemmatizer()

In [28]:
corpus=[]
for i in range(0,len(messages)):
    ## remove special characters
    review=re.sub('[^a-zA-z]', ' ', messages['message'][i]) ## This says- apart from small and capital a-z any other thing you find replace it with blankspace. Perform this is in the data provided
    review=review.lower()
    review_words=review.split()
    stemmed_review_words=[wnl.lemmatize(word) for word in review_words if not word in stopwords.words('english')]
    stemmed_review_sentence=' '.join(stemmed_review_words)
    corpus.append(stemmed_review_sentence)

In [29]:
corpus

['go jurong point crazy available bugis n great world la e buffet cine got amore wat',
 'ok lar joking wif u oni',
 'free entry wkly comp win fa cup final tkts st may text fa receive entry question std txt rate c apply',
 'u dun say early hor u c already say',
 'nah think go usf life around though',
 'freemsg hey darling week word back like fun still tb ok xxx std chgs send rcv',
 'even brother like speak treat like aid patent',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune caller press copy friend callertune',
 'winner valued network customer selected receivea prize reward claim call claim code kl valid hour',
 'mobile month u r entitled update latest colour mobile camera free call mobile update co free',
 'gonna home soon want talk stuff anymore tonight k cried enough today',
 'six chance win cash pound txt csh send cost p day day tsandcs apply reply hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw'

In [30]:
## Create TF-IDF and NGrams
from sklearn.feature_extraction.text import TfidfVectorizer

In [31]:
tfidf=TfidfVectorizer(max_features=100)
X=tfidf.fit_transform(corpus).toarray()

In [33]:
import numpy as np
np.set_printoptions(
    edgeitems=30,
    linewidth=100000,
    formatter=dict(float=lambda x: "%.3g" % x)
)

In [34]:
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.434, 0, 0, 0.461, 0.544, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.55, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.456, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0.473, 0, 0, 0, 0, 0, 0, 0, 0.492, 0, 0, 0, 0, 0, 0, 0, 0.571, 0, 0, 0, 0, 0, 0],
       [0.465, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.486, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.574, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [35]:
X.shape


(5572, 100)

## Word2Vec Practical Implementation

Please refer to notes for the mathematical intuition. We will be using `gensim` for this practical example.

In [1]:
!pip install gensim

Defaulting to user installation because normal site-packages is not writeable


In [2]:
import gensim

In [3]:
from gensim.models import Word2Vec, KeyedVectors

For the `pretrained implementation`, we will use **`word2vec-google-news-300`**. It can be dowloaded from `gensim`

In [11]:
import gensim.downloader as api
wv=api.load('word2vec-google-news-300')
vec_king=wv['king']

## This code checks the folder 'word2vec-google-news-300' (within gensim folder)
## If the compressed data is not present the __init__.py will fire a download request
## Sometimes the download may be unsuccessful due to some reasons, like network
## You can download it directly via your browser through this link
## https://github.com/piskvorky/gensim-data/releases/tag/word2vec-google-news-300?utm_source=chatgpt.com
## ensure you download the word2vec with the init file
## once its downloaded successfully move it to gensim folder in a word2vec-google-news-300 folder
## If it fails to download in google chrome, use Edge or Firefox


In [12]:
## THis is vector for the word 'King' with 300 dimensions
vec_king

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [6]:
print("BASE_DIR:", api.BASE_DIR)

BASE_DIR: C:\Users\pc/gensim-data


In [7]:
import tempfile
print(tempfile.gettempdir())

C:\Users\pc\AppData\Local\Temp


In [9]:
import gensim.downloader as api
print(api.BASE_DIR)

C:\Users\pc/gensim-data


In [13]:
vec_king.shape

(300,)

In [14]:
wv['cricket']

array([-3.67187500e-01, -1.21582031e-01,  2.85156250e-01,  8.15429688e-02,
        3.19824219e-02, -3.19824219e-02,  1.34765625e-01, -2.73437500e-01,
        9.46044922e-03, -1.07421875e-01,  2.48046875e-01, -6.05468750e-01,
        5.02929688e-02,  2.98828125e-01,  9.57031250e-02,  1.39648438e-01,
       -5.41992188e-02,  2.91015625e-01,  2.85156250e-01,  1.51367188e-01,
       -2.89062500e-01, -3.46679688e-02,  1.81884766e-02, -3.92578125e-01,
        2.46093750e-01,  2.51953125e-01, -9.86328125e-02,  3.22265625e-01,
        4.49218750e-01, -1.36718750e-01, -2.34375000e-01,  4.12597656e-02,
       -2.15820312e-01,  1.69921875e-01,  2.56347656e-02,  1.50146484e-02,
       -3.75976562e-02,  6.95800781e-03,  4.00390625e-01,  2.09960938e-01,
        1.17675781e-01, -4.19921875e-02,  2.34375000e-01,  2.03125000e-01,
       -1.86523438e-01, -2.46093750e-01,  3.12500000e-01, -2.59765625e-01,
       -1.06933594e-01,  1.04003906e-01, -1.79687500e-01,  5.71289062e-02,
       -7.41577148e-03, -

In [15]:
wv['Izu']

array([ 0.18847656,  0.24414062,  0.07519531, -0.18359375,  0.0090332 ,
        0.08056641, -0.15625   , -0.08789062, -0.25976562,  0.22949219,
        0.10009766,  0.15722656, -0.05688477, -0.08544922, -0.06787109,
       -0.05249023, -0.35546875,  0.20117188, -0.14160156, -0.03979492,
       -0.11279297, -0.03173828, -0.10058594,  0.109375  ,  0.02746582,
       -0.12109375, -0.12353516, -0.14648438,  0.13769531, -0.04980469,
        0.00242615, -0.10449219, -0.12158203,  0.01623535, -0.30273438,
       -0.32617188,  0.25195312, -0.09570312, -0.07275391, -0.16308594,
       -0.22949219,  0.05175781, -0.05273438,  0.24804688,  0.15234375,
        0.08447266,  0.18652344,  0.09423828, -0.03393555, -0.05615234,
       -0.12207031, -0.28710938,  0.24121094, -0.02001953,  0.00927734,
        0.29492188,  0.02966309, -0.02868652,  0.10888672, -0.5390625 ,
       -0.07714844,  0.36328125, -0.09619141, -0.23730469,  0.09570312,
       -0.31054688, -0.01519775,  0.07763672,  0.19824219, -0.06

In [16]:
## We can check for most similar words to a word
wv.most_similar('cricket')

[('cricketing', 0.8372225761413574),
 ('cricketers', 0.8165745735168457),
 ('Test_cricket', 0.8094819784164429),
 ('Twenty##_cricket', 0.8068488240242004),
 ('Twenty##', 0.7624265551567078),
 ('Cricket', 0.7541396617889404),
 ('cricketer', 0.7372578382492065),
 ('twenty##', 0.7316356897354126),
 ('T##_cricket', 0.7304614186286926),
 ('West_Indies_cricket', 0.698798656463623)]

The numbers sow the level of similarities. The closer it is to 1 the closer the similarities.

`It ranges from -1 to 1:`

* `1.0 → identical direction (very similar)`
* ` 0 → unrelated`
* ` -1 → opposite direction`

In [17]:
wv.most_similar('happy')

[('glad', 0.7408890724182129),
 ('pleased', 0.6632170677185059),
 ('ecstatic', 0.6626912355422974),
 ('overjoyed', 0.6599286794662476),
 ('thrilled', 0.6514049172401428),
 ('satisfied', 0.6437949538230896),
 ('proud', 0.636042058467865),
 ('delighted', 0.6272379159927368),
 ('disappointed', 0.6269949674606323),
 ('excited', 0.6247665882110596)]

In [18]:
## You can check the similarity between two words
wv.similarity("hockey","sports")

0.5354152

In [19]:
wv.similarity("bad","good") ## You can google why its not negative 

0.7190051

In [20]:
wv.similarity('banana','democracy')

0.14052573

In [22]:
wv.similarity('airplane', 'happiness')

0.101052366

I have been tryinf to find words that will give a negative cosine similarity. We will use code to fish it out.

In [23]:
import numpy as np

word = "good"

# Compute similarities with every word in the vocabulary
sims = wv.cosine_similarities(wv[word], wv.vectors)

# Get the index of the smallest similarity
idx = np.argmin(sims)

print(wv.index_to_key[idx])
print(sims[idx])

J.Gordon_###-###
-0.3913142


In [24]:
## lets do some operation
vec=wv['king']-wv['man']+wv['woman']
vec

array([ 4.29687500e-02, -1.78222656e-01, -1.29089355e-01,  1.15234375e-01,
        2.68554688e-03, -1.02294922e-01,  1.95800781e-01, -1.79504395e-01,
        1.95312500e-02,  4.09919739e-01, -3.68164062e-01, -3.96484375e-01,
       -1.56738281e-01,  1.46484375e-03, -9.30175781e-02, -1.16455078e-01,
       -5.51757812e-02, -1.07574463e-01,  7.91015625e-02,  1.98974609e-01,
        2.38525391e-01,  6.34002686e-02, -2.17285156e-02,  0.00000000e+00,
        4.72412109e-02, -2.17773438e-01, -3.44726562e-01,  6.37207031e-02,
        3.16406250e-01, -1.97631836e-01,  8.59375000e-02, -8.11767578e-02,
       -3.71093750e-02,  3.15551758e-01, -3.41796875e-01, -4.68750000e-02,
        9.76562500e-02,  8.39843750e-02, -9.71679688e-02,  5.17578125e-02,
       -5.00488281e-02, -2.20947266e-01,  2.29492188e-01,  1.26403809e-01,
        2.49023438e-01,  2.09960938e-02, -1.09863281e-01,  5.81054688e-02,
       -3.35693359e-02,  1.29577637e-01,  2.41699219e-02,  3.48129272e-02,
       -2.60009766e-01,  

In [25]:
wv.most_similar([vec])

[('king', 0.8449392318725586),
 ('queen', 0.7300518155097961),
 ('monarch', 0.645466148853302),
 ('princess', 0.6156251430511475),
 ('crown_prince', 0.5818676948547363),
 ('prince', 0.5777117609977722),
 ('kings', 0.5613664388656616),
 ('sultan', 0.5376776456832886),
 ('Queen_Consort', 0.5344247221946716),
 ('queens', 0.5289887189865112)]

This is `Pretrained Word2Vec` because we are using ready made vectors trained by google experts. Later on we will learn how to build our own vectors from scratch. 

For now we will go to doing a full machine learning analysis with what we have learned so far

## SPAM HAM PROJECT

Here we will develop a model to predict if a message is a spam or not. We will apply `BOW`, `TD-IDF` and `Machine Learning Algorithms`

In [28]:
import pandas as pd
messages = pd.read_csv('SMSSpamCollection.txt',sep='\t',names=['label','message'])

In [29]:
messages

,label,message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."
...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...
5568,ham,Will ü b going to esplanade fr home?
5569,ham,"Pity, * was in mood for that. So...any other s..."
5570,ham,The guy did some bitching but I acted like i'd...


In [30]:
## Data Cleaning And Preprocessing
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\pc\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [35]:
from nltk.corpus import stopwords
from nltk.stem import SnowballStemmer
sbs=SnowballStemmer('english')

In [36]:
corpus=[]
for i in range(0,len(messages)):
    review=re.sub('[^a-zA-z]',' ',messages['message'][i])
    review=review.lower()
    review=review.split()
    review=[sbs.stem(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)

In [37]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkts st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chgs send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breath

In [39]:
## CREATE BAG OF WORDS MODEL
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=100)

In [40]:
X=cv.fit_transform(corpus).toarray()

In [ ]:
import numpy as np
np.set_printoptions(
    edgeitems=30,
    linewidth=100000,
    formatter=dict(float=lambda x: "%.3g" % x))

X